Import('Env')
Env = Env.Clone()

deplibs = [
    'spdlog',
    'glog',
    'gtest',
    'pthread',
    'gflags'
]


objfiles = [
    'timestamp.cc',
    'thread_pool.cc'
]

TARGET_LIB = 'base'
Env.Library(TARGET_LIB, Env.Object(objfiles))

deplibs.insert(0, TARGET_LIB)

Env.Program('thread_pool_unittest', source=['thread_pool_unittest.cc'], LIBS=deplibs)
Env.Program('object_pool_unittest', source=['object_pool_unittest.cc'], LIBS=deplibs)
