Import ('Env')
Env = Env.Clone()

deplibs = [
    'spdlog',
    'glog',
    'gtest',
    'pthread',
    'gflags'
]

Env.Program('skiplist_unittest', source=['skiplist_unittest.cc'], LIBS=deplibs)
Env.Program('linklist_unittest', source=['linklist_unittest.cc'], LIBS=deplibs)