Import('Env')
Env = Env.Clone()

deplibs = [
    'spdlog',
    'glog',
    'gtest',
    'pthread',
    'gflags'
]

objfiles = [
    'sort.cc',
    'array.cc',
    'str.cc'
]

TARGET_LIB = 'algorithm'
Env.Library(TARGET_LIB, Env.Object(objfiles))

deplibs.insert(0, TARGET_LIB)

Env.Program('alg_unittest', source=['alg_unittest.cc'], LIBS=deplibs)

