Import ('Env')
Env = Env.Clone()
deplibs = [
    'spdlog',
    'glog',
    'gtest',
    'pthread',
    'gflags'
]

objfiles = [
    'sort.cc',
    'array.cc'
]

Env.Library('algorithm', Env.Object(objfiles))
deplibs.append('algorithm')

Env.Program('sort_unittest', source=['sort_unittest.cc'], LIBS=deplibs)
